-- MySQL Script generated by MySQL Workbench
-- Dom 21 Jun 2015 17:10:17 BRT
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_email_poll
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_email_poll` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `db_email_poll` ;

-- -----------------------------------------------------
-- Table `db_email_poll`.`tb_person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_email_poll`.`tb_person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT NULL,
  `email` TEXT NULL,
  `tel` TEXT NULL,
  `comment` TEXT NULL,
  `hash` TEXT NULL,
  `creation_dt` DATETIME NULL,
  `password` TEXT NULL,
  `timezone` INT NULL,
  `image` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_email_poll`.`tb_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_email_poll`.`tb_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT NULL,
  `description` TEXT NULL,
  `hash` TEXT NULL,
  `creation_dt` DATETIME NULL,
  `tb_person_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tb_person_id`),
  INDEX `fk_tb_group_tb_person_idx` (`tb_person_id` ASC),
  CONSTRAINT `fk_tb_group_tb_person`
    FOREIGN KEY (`tb_person_id`)
    REFERENCES `db_email_poll`.`tb_person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_email_poll`.`tb_poll`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_email_poll`.`tb_poll` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` TEXT NULL,
  `options` TEXT NULL,
  `hash` TEXT NULL,
  `creation_dt` DATETIME NULL,
  `tb_group_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tb_group_id`),
  INDEX `fk_tb_poll_tb_group1_idx` (`tb_group_id` ASC),
  CONSTRAINT `fk_tb_poll_tb_group1`
    FOREIGN KEY (`tb_group_id`)
    REFERENCES `db_email_poll`.`tb_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_email_poll`.`tb_vote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_email_poll`.`tb_vote` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` INT NULL,
  `comment` TEXT NULL,
  `vote_dt` DATETIME NULL,
  `tb_person_id` INT NOT NULL,
  `tb_poll_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tb_person_id`, `tb_poll_id`),
  INDEX `fk_tb_vote_tb_person1_idx` (`tb_person_id` ASC),
  INDEX `fk_tb_vote_tb_poll1_idx` (`tb_poll_id` ASC),
  CONSTRAINT `fk_tb_vote_tb_person1`
    FOREIGN KEY (`tb_person_id`)
    REFERENCES `db_email_poll`.`tb_person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_vote_tb_poll1`
    FOREIGN KEY (`tb_poll_id`)
    REFERENCES `db_email_poll`.`tb_poll` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_email_poll`.`tb_log_lines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_email_poll`.`tb_log_lines` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `log` TEXT NULL,
  `tb_group_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tb_group_id`),
  INDEX `fk_tb_log_lines_tb_group1_idx` (`tb_group_id` ASC),
  CONSTRAINT `fk_tb_log_lines_tb_group1`
    FOREIGN KEY (`tb_group_id`)
    REFERENCES `db_email_poll`.`tb_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_email_poll`.`tb_person_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_email_poll`.`tb_person_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tb_person_id` INT NOT NULL,
  `tb_group_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tb_person_id`),
  INDEX `fk_tb_person_group_tb_person1_idx` (`tb_person_id` ASC),
  INDEX `fk_tb_person_group_tb_group1_idx` (`tb_group_id` ASC),
  CONSTRAINT `fk_tb_person_group_tb_person1`
    FOREIGN KEY (`tb_person_id`)
    REFERENCES `db_email_poll`.`tb_person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_person_group_tb_group1`
    FOREIGN KEY (`tb_group_id`)
    REFERENCES `db_email_poll`.`tb_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
